-- Inicialización de la Base de Datos Transaccional (db_default)
SET search_path TO public;

-- 1. Creación de Tablas Operativas Nativas
CREATE TABLE public."Alumno" (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    no_cuenta character varying UNIQUE,
    nombre character varying,
    apellidos character varying,
    plan_estudio_id integer,
    correo character varying(150) UNIQUE,
    contrasena character varying(128)
);

CREATE TABLE public."Horarios" (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profesor_id integer,
    cve_asignatura character varying,
    grupo character varying,
    tipo character varying,
    "LunMarMieJueVieSab" character varying,
    salon character varying,
    cupo integer
);

CREATE TABLE public."Inscripcion" (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumno_id integer REFERENCES public."Alumno"(id) DEFERRABLE,
    "Horarios_id" integer REFERENCES public."Horarios"(id) DEFERRABLE,
    cve_asignatura character varying,
    fecha_inscripcion timestamp without time zone
);

CREATE UNIQUE INDEX "Inscripcion_alumno_id_cve_asignatura_idx" ON public."Inscripcion" USING btree (alumno_id, cve_asignatura);

-- 2. Inyección de Datos Reales Poblados
INSERT INTO public."Alumno" (id, no_cuenta, nombre, apellidos, plan_estudio_id, correo, contrasena) VALUES 
(1, '320139105', 'Eder', 'Alvarez Macias', 3, 'ederalvarez05@aragon.unam.mx', 'pbkdf2_sha256$600000$oQlkVJbOFjpXMpV1oFCHoT$REpHZFGHm3hz5P2q0ldgobsKuCVQRGjyy0vGTeMOzjE='),
(2, '320334249', 'Eder', 'Avalos Juarez', 3, 'ederavalos32@aragon.unam.mx', 'pbkdf2_sha256$600000$oQlkVJbOFjpXMpV1oFCHoT$REpHZFGHm3hz5P2q0ldgobsKuCVQRGjyy0vGTeMOzjE='),
(3, '423082292', 'Arturo Ivan', 'Azuara Ocotitla', 3, 'arturoazuara92@aragon.unam.mx', 'pbkdf2_sha256$600000$oQlkVJbOFjpXMpV1oFCHoT$REpHZFGHm3hz5P2q0ldgobsKuCVQRGjyy0vGTeMOzjE='),
(4, '329282438', 'Josue Ricardo', 'Enriquez Garcia', 3, 'ricardoenriquez@aragon.unam.mx', 'pbkdf2_sha256$600000$oQlkVJbOFjpXMpV1oFCHoT$REpHZFGHm3hz5P2q0ldgobsKuCVQRGjyy0vGTeMOzjE='),
(5, '320987665', 'Diego Rodrigo', 'Soto Franco', 3, 'soto@aragon.unam.mx', 'pbkdf2_sha256$600000$oQlkVJbOFjpXMpV1oFCHoT$REpHZFGHm3hz5P2q0ldgobsKuCVQRGjyy0vGTeMOzjE='),
(6, '320305350', 'Alexis', 'Trujillo Torres', 3, 'alexistrujillo@aragon.unam.mx', 'pbkdf2_sha256$600000$oQlkVJbOFjpXMpV1oFCHoT$REpHZFGHm3hz5P2q0ldgobsKuCVQRGjyy0vGTeMOzjE='),
(7, '316098292', 'Xchel', 'Jaimes Ruiz', 3, 'xcheljaimes@aragon.unam.mx', 'pbkdf2_sha256$600000$oQlkVJbOFjpXMpV1oFCHoT$REpHZFGHm3hz5P2q0ldgobsKuCVQRGjyy0vGTeMOzjE='),
(8, '320249617', 'Paula Mabel', 'Hernandez Ruiz', 3, 'paula@aragon.unam.mx', 'pbkdf2_sha256$600000$oQlkVJbOFjpXMpV1oFCHoT$REpHZFGHm3hz5P2q0ldgobsKuCVQRGjyy0vGTeMOzjE='),
(9, '319154412', 'José Ignacio', 'Iniestra Hernández', 3, 'ignacioiniestra12@aragon.unam.mx', 'pbkdf2_sha256$600000$oQlkVJbOFjpXMpV1oFCHoT$REpHZFGHm3hz5P2q0ldgobsKuCVQRGjyy0vGTeMOzjE='),
(10, '320084225', 'Christian Gael', 'Lara Martinez', 3, 'claram@aragon.unam.mx', 'pbkdf2_sha256$600000$oQlkVJbOFjpXMpV1oFCHoT$REpHZFGHm3hz5P2q0ldgobsKuCVQRGjyy0vGTeMOzjE='),
(11, '320085590', 'Jorge Mauricio', 'Maldonado Amaro', 3, 'jorgemauricio59@aragon.unam.mx', 'pbkdf2_sha256$600000$oQlkVJbOFjpXMpV1oFCHoT$REpHZFGHm3hz5P2q0ldgobsKuCVQRGjyy0vGTeMOzjE='),
(12, '423071182', 'Manuel Alberto', 'Manzana Calixto', 3, 'manuelcalixto82@aragon.unam.mx', 'pbkdf2_sha256$600000$oQlkVJbOFjpXMpV1oFCHoT$REpHZFGHm3hz5P2q0ldgobsKuCVQRGjyy0vGTeMOzjE='),
(13, '314776555', 'Eliezer Isaí', 'Monroy Quintero', 3, 'isai@aragon.unam.mx', 'pbkdf2_sha256$600000$oQlkVJbOFjpXMpV1oFCHoT$REpHZFGHm3hz5P2q0ldgobsKuCVQRGjyy0vGTeMOzjE='),
(14, '320320402', 'Eden Arturo', 'Moreno Diaz', 3, 'edendiaz02@aragon.unam.mx', 'pbkdf2_sha256$600000$oQlkVJbOFjpXMpV1oFCHoT$REpHZFGHm3hz5P2q0ldgobsKuCVQRGjyy0vGTeMOzjE='),
(15, '320071609', 'Mónica Alessandra', 'Padrón Cortes', 3, 'monicapadron09@aragon.unam.mx', 'pbkdf2_sha256$600000$oQlkVJbOFjpXMpV1oFCHoT$REpHZFGHm3hz5P2q0ldgobsKuCVQRGjyy0vGTeMOzjE='),
(16, '320000000', 'Humberto', 'Trujillo Maldonado', 3, 'humbertotrujillo125@aragon.unam.mx', 'pbkdf2_sha256$600000$oQlkVJbOFjpXMpV1oFCHoT$REpHZFGHm3hz5P2q0ldgobsKuCVQRGjyy0vGTeMOzjE='),
(17, '320170516', 'Omar', 'Vilchis Ibarra', 3, 'omar@aragon.unam.mx', 'pbkdf2_sha256$600000$oQlkVJbOFjpXMpV1oFCHoT$REpHZFGHm3hz5P2q0ldgobsKuCVQRGjyy0vGTeMOzjE='),
(18, '320235469', 'Sebastian', 'Villarreal Mora', 3, 'sebastianvillarreal59@aragon.unam.mx', 'pbkdf2_sha256$600000$oQlkVJbOFjpXMpV1oFCHoT$REpHZFGHm3hz5P2q0ldgobsKuCVQRGjyy0vGTeMOzjE='),
(19, '316248766', 'Aksel', 'Villela Andrade', 3, 'aksel@aragon.unam.mx', 'pbkdf2_sha256$600000$oQlkVJbOFjpXMpV1oFCHoT$REpHZFGHm3hz5P2q0ldgobsKuCVQRGjyy0vGTeMOzjE='),
(20, '320116500', 'Emiliano', 'Zuno Velazquez', 3, 'emilianozuno00@aragon.unam.mx', 'pbkdf2_sha256$600000$oQlkVJbOFjpXMpV1oFCHoT$REpHZFGHm3hz5P2q0ldgobsKuCVQRGjyy0vGTeMOzjE=');
SELECT setval('public."Alumno_id_seq"', 20, true);

INSERT INTO public."Horarios" (id, profesor_id, cve_asignatura, grupo, tipo, "LunMarMieJueVieSab", salon, cupo) VALUES 
(6, NULL, '0167', '2008', 'A DISTANCIA', 'MAR-JUE 09:00-11:00', 'VIRTUAL', 60),
(7, NULL, '0170', '2008', 'PRESENCIAL', 'LUN-MIE-VIE 10:00-11:30', 'A213', 60),
(8, NULL, '1627', '2008', 'PRESENCIAL', 'MAR-JUE 11:00-13:00', 'A8120', 30),
(10, NULL, '2138', '2008', 'PRESENCIAL', 'LUN-MIE-VIE 10:00-11:20', 'A11203', 40),
(14, 1, '0712', '2501', 'O', 'Lunes y Miércoles de 07:00 a 09:00', 'A-101', 40),
(11, NULL, '8701', '2008', 'PRESENCIAL', 'LUN-MIE-VIE 10:00-11:20', 'A11203', 41),
(18, 5, '1522', '2501', 'L', 'Viernes de 07:00 a 11:00 (Laboratorio)', 'L-Comp', 20),
(26, 11, '1418', '2551', 'O', 'Lunes y Miércoles de 17:00 a 19:00', 'A-202', 45),
(9, NULL, '2128', '2008', 'PRESENCIAL', 'LUN-MIE-VIE 11:00-12:20', 'A8121', 27),
(1, 1, '0712', '2407', 'PRESENCIAL', 'LUN-MIE-VIE 07:00-08:30', 'A506', 51),
(3, 3, '1418', '2407', 'PRESENCIAL', 'MAR-JUE 07:00-09:00', 'A205', 56),
(2, 2, '1417', '2407', 'PRESENCIAL', 'LUN-MIE-VIE 08:40-10:00', 'A203', 61),
(4, 4, '0442', '2507', 'PRESENCIAL', 'LUN-MIE-VIE 08:40-10:00', 'A8119', 26),
(59, 24, '0420', '2401', 'O', 'Lunes y Miércoles de 07:00 a 09:00', 'A-105', 40),
(17, 4, '1419', '2501', 'O', 'Martes y Jueves de 09:00 a 11:00', 'A-101', 40),
(60, 4, '0829', '2401', 'O', 'Martes y Jueves de 07:00 a 09:00', 'A-105', 40),
(61, 25, '0912', '2401', 'O', 'Lunes y Miércoles de 09:00 a 11:00', 'A-106', 40),
(62, 5, '1314', '2401', 'O', 'Martes y Jueves de 09:00 a 11:00', 'A-105', 40),
(63, 26, '1422', '2401', 'L', 'Viernes de 07:00 a 11:00 (Laboratorio)', 'L-Hard', 20),
(64, 24, '0420', '2402', 'O', 'Lunes y Miércoles de 09:00 a 11:00', 'A-107', 40),
(65, 27, '0829', '2402', 'O', 'Martes y Jueves de 09:00 a 11:00', 'A-107', 40),
(66, 25, '0912', '2402', 'O', 'Lunes y Miércoles de 11:00 a 13:00', 'A-108', 40),
(67, 28, '1314', '2402', 'O', 'Martes y Jueves de 11:00 a 13:00', 'A-107', 40),
(68, 26, '1422', '2402', 'L', 'Viernes de 11:00 a 15:00 (Laboratorio)', 'L-Hard', 20),
(69, 29, '0420', '2451', 'O', 'Lunes y Miércoles de 15:00 a 17:00', 'A-203', 45),
(70, 30, '0829', '2451', 'O', 'Martes y Jueves de 15:00 a 17:00', 'A-203', 45),
(71, 11, '0912', '2451', 'O', 'Lunes y Miércoles de 17:00 a 19:00', 'A-204', 45),
(72, 28, '1314', '2451', 'O', 'Martes y Jueves de 17:00 a 19:00', 'A-203', 45),
(73, 26, '1422', '2451', 'L', 'Viernes de 15:00 a 19:00 (Laboratorio)', 'L-Hard', 25),
(74, 31, '0642', '2601', 'O', 'Lunes y Miércoles de 07:00 a 09:00', 'B-101', 40),
(75, 32, '1323', '2601', 'O', 'Martes y Jueves de 07:00 a 09:00', 'B-101', 40),
(76, 2, '1500', '2601', 'O', 'Lunes y Miércoles de 09:00 a 11:00', 'B-102', 40),
(77, 33, '1503', '2601', 'O', 'Martes y Jueves de 09:00 a 11:00', 'B-101', 40),
(78, 34, '1611', '2601', 'L', 'Viernes de 07:00 a 11:00 (Laboratorio)', 'L-Soft', 20),
(79, 31, '0642', '2602', 'O', 'Lunes y Miércoles de 09:00 a 11:00', 'B-103', 40),
(80, 35, '1323', '2602', 'O', 'Martes y Jueves de 09:00 a 11:00', 'B-103', 40),
(81, 3, '1500', '2602', 'O', 'Lunes y Miércoles de 11:00 a 13:00', 'B-104', 40),
(82, 33, '1503', '2602', 'O', 'Martes y Jueves de 11:00 a 13:00', 'B-103', 40),
(83, 34, '1611', '2602', 'L', 'Viernes de 11:00 a 15:00 (Laboratorio)', 'L-Soft', 20),
(23, 5, '1522', '2502', 'L', 'Viernes de 11:00 a 15:00 (Laboratorio)', 'L-Hard', 20),
(16, 3, '1418', '2501', 'O', 'Lunes y Miércoles de 09:00 a 11:00', 'A-102', 40),
(20, 6, '1417', '2502', 'O', 'Martes y Jueves de 09:00 a 11:00', 'A-103', 40),
(19, 1, '0712', '2502', 'O', 'Lunes y Miércoles de 09:00 a 11:00', 'A-103', 40),
(21, 8, '1418', '2502', 'O', 'Lunes y Miércoles de 11:00 a 13:00', 'A-104', 39),
(15, 2, '1417', '2501', 'O', 'Martes y Jueves de 07:00 a 09:00', 'A-101', 39),
(27, 12, '1419', '2551', 'O', 'Martes y Jueves de 17:00 a 19:00', 'A-201', 44),
(5, 13, '1500', '2507', 'PRESENCIAL', 'MAR-JUE 09:00-11:00', 'A11202', 44),
(28, 13, '1522', '2551', 'L', 'Viernes de 15:00 a 19:00 (Laboratorio)', 'L-Comp', 24),
(25, 10, '1417', '2551', 'O', 'Martes y Jueves de 15:00 a 17:00', 'A-201', 44),
(22, 7, '1419', '2502', 'O', 'Martes y Jueves de 11:00 a 13:00', 'A-103', 39),
(24, 9, '0712', '2551', 'O', 'Lunes y Miércoles de 15:00 a 17:00', 'A-201', 44),
(13, 7, '0442', '2508', 'PRESENCIAL', 'LUN-MIE-VIE 08:40-10:00', 'A11202', 0),
(84, 36, '0642', '2651', 'O', 'Lunes y Miércoles de 15:00 a 17:00', 'B-201', 45),
(85, 32, '1323', '2651', 'O', 'Martes y Jueves de 15:00 a 17:00', 'B-201', 45),
(86, 21, '1500', '2651', 'O', 'Lunes y Miércoles de 17:00 a 19:00', 'B-202', 45),
(87, 37, '1503', '2651', 'O', 'Martes y Jueves de 17:00 a 19:00', 'B-201', 45),
(88, 34, '1611', '2651', 'L', 'Viernes de 15:00 a 19:00 (Laboratorio)', 'L-Soft', 25),
(89, 38, '0722', '2701', 'O', 'Lunes y Miércoles de 07:00 a 09:00', 'B-105', 40),
(90, 39, '1704', '2701', 'O', 'Martes y Jueves de 07:00 a 09:00', 'B-105', 40),
(91, 40, '1708', '2701', 'O', 'Lunes y Miércoles de 09:00 a 11:00', 'B-106', 40),
(92, 41, '1712', '2701', 'O', 'Martes y Jueves de 09:00 a 11:00', 'B-105', 40),
(93, 42, '1715', '2701', 'L', 'Viernes de 07:00 a 11:00 (Laboratorio)', 'L-Redes', 20),
(94, 38, '0722', '2702', 'O', 'Lunes y Miércoles de 09:00 a 11:00', 'B-107', 40),
(95, 16, '1704', '2702', 'O', 'Martes y Jueves de 09:00 a 11:00', 'B-107', 40),
(96, 40, '1708', '2702', 'O', 'Lunes y Miércoles de 11:00 a 13:00', 'B-108', 40),
(97, 41, '1712', '2702', 'O', 'Martes y Jueves de 11:00 a 13:00', 'B-107', 40),
(98, 42, '1715', '2702', 'L', 'Viernes de 11:00 a 15:00 (Laboratorio)', 'L-Redes', 20),
(99, 38, '0722', '2751', 'O', 'Lunes y Miércoles de 15:00 a 17:00', 'B-203', 45),
(100, 39, '1704', '2751', 'O', 'Martes y Jueves de 15:00 a 17:00', 'B-203', 45),
(101, 17, '1708', '2751', 'O', 'Lunes y Miércoles de 17:00 a 19:00', 'B-204', 45),
(102, 41, '1712', '2751', 'O', 'Martes y Jueves de 17:00 a 19:00', 'B-203', 45),
(103, 42, '1715', '2751', 'L', 'Viernes de 15:00 a 19:00 (Laboratorio)', 'L-Redes', 10);
SELECT setval('public."Horarios_id_seq"', 103, true);

-- Inyección opcional por si quieres dejar las inscripciones de prueba activas
INSERT INTO public."Inscripcion" (id, alumno_id, "Horarios_id", cve_asignatura, fecha_inscripcion) VALUES 
(1, 1, 25, '1417', '2026-05-17 21:20:49.610733'),
(2, 1, 22, '1419', '2026-05-17 21:20:58.981787'),
(3, 1, 24, '0712', '2026-05-17 21:50:48.619346'),
(4, 1, 13, '0442', '2026-05-17 21:54:17.07465');
SELECT setval('public."Inscripcion_id_seq"', 4, true);