"""
Django settings for sistema_fes_aragon project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@g!8^8_ru8@lqy7=3pw_vtd!v8%j)1aj&$ie5#dhub&6qkcn6e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inscripciones',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sistema_fes_aragon.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sistema_fes_aragon.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'inscripciones_default',
        'USER': 'eder_admin',
        'PASSWORD': 'password_seguro_1',
        'HOST': 'db_default', # <-- El nombre del servicio en docker-compose
        'PORT': '5432',
    },
    'staging_db': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'inscripciones_staging',
        'USER': 'eder_admin',
        'PASSWORD': 'password_seguro_2',
        'HOST': 'db_staging', # <-- El nombre del servicio en docker-compose
        'PORT': '5432',       # Dentro de Docker corre en su puerto interno 5432
        'OPTIONS': {
            'options': '-c search_path=staging,public'
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================================================================
# CONFIGURACIÓN DEFINITIVA DE JAZZMIN (DISTRIBUCIÓN Y IDENTIDAD ELEGANTE)
# ==============================================================================
JAZZMIN_SETTINGS = {
    "site_title": "Admin Inscripciones FES",
    "site_header": "FES Aragón — Control Escolar",
    "site_brand": "Inscripciones Computación",
    "welcome_sign": "Sistema de Gestión de Inscripciones (DB2)",
    "copyright": "Facultad de Estudios Superiores Aragón UNAM",
    
    "search_model": ["inscripciones.Alumno"],
    "custom_css": "inscripciones/css/custom_admin.css",  # ¡Aquí inyectaremos la magia!

    "icons": {
        "auth.user": "fas fa-user-shield",
        "auth.group": "fas fa-users-cog",
        "inscripciones.alumno": "fas fa-user-graduate",
        "inscripciones.inscripcion": "fas fa-file-signature",
        "inscripciones.horarios": "fas fa-calendar-alt",
        "inscripciones.asignatura": "fas fa-book",
        "inscripciones.profesor": "fas fa-chalkboard-teacher",
        "inscripciones.planestudio": "fas fa-scroll",
    },
    
    # Propiedad correcta de Jazzmin para ordenar el menú lateral
    "order_with_respect_to": [
        "inscripciones.alumno",
        "inscripciones.inscripcion",
        "inscripciones.horarios",
        "inscripciones.asignatura",
        "inscripciones.profesor",
        "inscripciones.planestudio",
        "auth.user",
        "auth.group"
    ],

    "topmenu_links": [
        {"name": "Dashboard Central", "url": "admin:index", "permissions": ["auth.change_user"]},
        {"name": "Ver Ventana de Alumnos", "url": "/", "new_window": True},
    ],
    
    "show_sidebar": True,
    "navigation_expanded": True,
}

# Configuración estructural de la interfaz de Jazzmin
JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",  # Base limpia y minimalista
    "dark_mode_theme": None,
    "navbar_fixed": True,
    "sidebar_fixed": True,
    "sidebar_nav_child_indent": True,
    "no_navbar_border": True,
    # Clases base que luego reescribiremos con el CSS personalizado
    "navbar": "navbar-dark bg-dark",
    "sidebar": "sidebar-dark-navy",
    "brand_colour": "navbar-dark bg-dark",
}