"""
Django settings for sistema_fes_aragon project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@g!8^8_ru8@lqy7=3pw_vtd!v8%j)1aj&$ie5#dhub&6qkcn6e'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'inscripciones',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sistema_fes_aragon.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sistema_fes_aragon.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'inscripciones_default',
        'USER': 'eder_admin',
        'PASSWORD': 'password_seguro_1',
        'HOST': 'db_default', # <-- El nombre del servicio en docker-compose
        'PORT': '5432',
    },
    'staging_db': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'inscripciones_staging',
        'USER': 'eder_admin',
        'PASSWORD': 'password_seguro_2',
        'HOST': 'db_staging', # <-- El nombre del servicio en docker-compose
        'PORT': '5432',       # Dentro de Docker corre en su puerto interno 5432
        'OPTIONS': {
            'options': '-c search_path=staging,public'
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================================================================
# CONFIGURACIÓN DEFINITIVA DE JAZZMIN (DISTRIBUCIÓN Y IDENTIDAD ELEGANTE)
# ==============================================================================
JAZZMIN_SETTINGS = {
    # Títulos de Identidad Institucional FES Aragón
    "site_title": "Admin Inscripciones FES",
    "site_header": "FES Aragón — Control Escolar",
    "site_brand": "Inscripciones Computación",
    "welcome_sign": "Bienvenido al Sistema de Gestión de Inscripciones (DB2)",
    "copyright": "Facultad de Estudios Superiores Aragón UNAM",
    
    # Buscador global rápido en la barra superior
    "search_model": ["inscripciones.Alumno"],

    # Inyección de estilos CSS sincronizados con panel.html
    "custom_css": "inscripciones/css/custom_admin.css",

    # 1. MAPEADO DE ICONOS VECTORIALES (FontAwesome)
    "icons": {
        "auth.user": "fas fa-user-shield",
        "auth.group": "fas fa-users-cog",
        "inscripciones.alumno": "fas fa-user-graduate",
        "inscripciones.inscripcion": "fas fa-file-signature",
        "inscripciones.horarios": "fas fa-calendar-alt",
        "inscripciones.asignatura": "fas fa-book",
        "inscripciones.profesor": "fas fa-chalkboard-teacher",
        "inscripciones.planestudio": "fas fa-scroll",
    },
    
    # 2. ORDENAMIENTO ESTRICTO DE SECCIONES (Sustituye por la propiedad correcta que lee Jazzmin)
    "reorder_with_respect_to": [
        # Bloque Principal: Operación Masiva
        "inscripciones.alumno",
        "inscripciones.inscripcion",
        # Bloque Secundario: Control Escolar de 5to Semestre
        "inscripciones.horarios",
        # Bloque Bajo: Catálogos Estáticos
        "inscripciones.asignatura",
        "inscripciones.profesor",
        "inscripciones.planestudio",
        # Seguridad de Django hasta el fondo
        "auth.user",
        "auth.group"
    ],

    # 3. MENÚ DE CONTROL SUPERIOR
    "topmenu_links": [
        {"name": "Dashboard Central", "url": "admin:index", "permissions": ["auth.change_user"]},
        {"name": "Ir a Ventana de Alumnos", "url": "/", "new_window": True},
    ],
    
    # Ajustes estructurales de barras de navegación
    "usermenu_links": [],
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # 4. AGRUPACIÓN COMPACTA (Evita que las tablas desaparezcan del centro)
    # Dejamos que Django ordene el dashboard con "reorder_with_respect_to", pero si quieres 
    # un acceso directo unificado a configuraciones base, lo mapeamos aquí:
    "custom_links": {
        "inscripciones": [{
            "name": "Seguridad e Identidades",
            "url": "/admin/auth/user/",
            "icon": "fas fa-shield-alt",
        }]
    },
}

JAZZMIN_UI_TUNER = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark bg-dark", 
    "actions_sidebar": False,
    "main_sidebar": "sidebar-dark-navy", # Azul marino corporativo profundo
    "sidebar_nav_child_indent": True,
    "navbar": "navbar-dark bg-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-navy",
    "sidebar_nav_flat_style": False,
    "theme": "flatly", 
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}