# Generated by Django 4.2 on 2026-05-17 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(blank=True, max_length=50, null=True)),
                ('correo_ins', models.EmailField(max_length=254, unique=True)),
                ('estatus_academico', models.BooleanField(default=True)),
                ('semestre_actual', models.IntegerField(default=1)),
                ('hora_acceso', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('creditos', models.IntegerField()),
                ('lab', models.BooleanField(default=False)),
                ('obl', models.BooleanField(default=True)),
                ('semestre', models.IntegerField(help_text='Semestre al que pertenece')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(blank=True, max_length=50, null=True)),
                ('correo_ins', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupo', models.IntegerField()),
                ('asig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.asignatura')),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscripciones.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('APARTADO', 'En Carrito'), ('FINALIZADO', 'Inscrito')], default='APARTADO', max_length=15)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.alumno')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscripciones.grupo')),
            ],
            options={
                'unique_together': {('alumno', 'grupo')},
            },
        ),
    ]
